#!/bin/bash

thomasv_pubkey="0x6694D8DE7BE8EE5631BED9502BD5824B7F9470E6"

if [ -z "$1" ]
then
	echo "Usage $0 [version]"
	exit 1
fi

curdir=`pwd`
version="$1"
tempdir="/tmp/electrum-install/$version"
mkdir -p $tempdir
cd $tempdir

filename="electrum-$version-x86_64.AppImage"
gpgsigfilename="$filename.ThomasV.asc"
if [ ! -f "$filename" ]
then 
	wget https://download.electrum.org/$version/$filename 
fi

if [ ! -f "$gpgsigfilename" ]
then
	wget https://download.electrum.org/$version/$gpgsigfilename 
fi

gpg --list-keys $thomasv_pubkey || gpg --recv-keys $thomasv_pubkey || wget https://github.com/spesmilo/electrum/raw/3.3.4/pubkeys/ThomasV.asc -O - | gpg --import  
gpg --verify $gpgsigfilename $filename

if [ $? -eq 0 ]
then
	response="n"
	read -p "GPG sig checks out. Proceed with installation (N,y): " response
	if [ "$response" == "y" ]
	then
		echo "Proceeding with install"

		electrum_dir="$HOME/bin"
		electrum_bin="$electrum_dir/electrum"
		mkdir -p $electrum_dir
		if [ -f "$electrum_bin" ]
		then
			rm $electrum_bin
		fi
		cp $filename $electrum_bin
		chmod +x $electrum_bin
		
		echo "To run electrum just type $electrum_bin from any terminal app. You can also create a shortcut to $electrum_bin on your desktop"
	else
		echo "Not proceeding with install"
	fi
else 
	echo "GPG sig check failed!"
fi

echo "Cleaning up..."
rm $filename $gpgsigfilename
cd $curdir
